---
title: "EMS Santa Monica"
author: "Anna Duan, Bingchu Chen"
date: "11/23/2020"
output: html_document
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
#Motivatioin

#Data and Methods

```{r load packages, message=FALSE, warning=FALSE, include=TRUE, results='hide', cache=TRUE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
options(scipen=10000000)
library(tidyverse)
library(sf)
library(RSocrata)
library(viridis)
library(spatstat)
library(raster)
library(spdep)
library(FNN)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
library(tidycensus)
library(mapview)
library(devtools)
library(lubridate)
library(dplyr)
root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source_url("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
paletteGray <- c("gray90", "gray70", "gray50", "gray30", "gray10")


plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.2),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))


palette5 <- c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c")
palette4 <- c("#D2FBD4","#92BCAB","#527D82","#123F5A")
palette2 <- c("#6baed6","#08519c")


# NEAREST NEIGHBOR FUNCTION
nn_function <- function(measureFrom,measureTo,k) {
  measureFrom_Matrix <-
    as.matrix(measureFrom)
  measureTo_Matrix <-
    as.matrix(measureTo)
  nn <-   
    get.knnx(measureTo, measureFrom, k)$nn.dist
    output <-
      as.data.frame(nn) %>%
      rownames_to_column(var = "thisPoint") %>%
      gather(points, point_distance, V1:ncol(.)) %>%
      arrange(as.numeric(thisPoint)) %>%
      group_by(thisPoint) %>%
      summarize(pointDistance = mean(point_distance)) %>%
      arrange(as.numeric(thisPoint)) %>% 
      dplyr::select(-thisPoint) %>%
      pull()
  return(output) 
}
```


```{r wrangle data, cache=TRUE}

#SM Base
SM_Base <- st_read("/Users/annaduan/Documents/GitHub/EMS-Prediction/SMTracts") %>%
  st_union() %>%
    st_transform('EPSG:2225')

#expanded SM base to capture additional fishnet cells
#SM_Buffer <- SM_Base %>%
#  st_buffer(.,6000)

#Census
census_api_key("d9ebfd04caa0138647fbacd94c657cdecbf705e9", install = TRUE, overwrite = TRUE)
#row 1: vacant, total housing units, mhhinc
#row 2: white, population, renter occ, owner occ, #no HS degree
#row 3: male adults, female adults, poverty level, youth unemployed (18-34, veteran), youth unemployed (non veteran)
#row 4-5: male 15-17, male 18-19, male 20, male 21, male 22-24, male 25-29, male 30-34
#row 6-7: female 18-34, 
###MEDIAN AGE TOTAL, male, female

dd18_5 <- load_variables(year = 2018,dataset = "acs5", cache = TRUE)

ACS <-
  get_acs(geography = "tract", variables = c("B25002_003E", "B25001_001E", "B19013_001E", "B01001A_001E", "B01003_001E", "B07013_002E", "B07013_003E", "B06009_002E", 
"B05003_008E", "B05003_019E", "B06012_002", "B21005_006E", "B21005_011E", 
"B01001_006E", "B01001_007E", "B01001_008E", "B01001_009E","B01001_010E", "B01001_011E", "B01001_012E",
"B01001_031E", "B01001_032E", "B01001_033E", "B01001_034E", "B01001_035E", "B01001_036E",
"B01002_001E", "B01002_002E","B01002_003E"), year=2018, state=06, county=037, geometry=T) %>%
    st_transform('EPSG:2225')

ACSTracts <- 
  ACS %>%
  as.data.frame() %>%
  distinct(GEOID, .keep_all = TRUE) %>%
  dplyr::select(GEOID, geometry) %>% 
  st_sf %>%
  st_transform('EPSG:2225')

###need to subset here
ACSTracts <- 
#####

ACS <-
  rbind(
    st_centroid(ACS)[SM_Base,] %>%
      st_drop_geometry() %>%
      left_join(ACS) %>%
      st_sf() %>%
      mutate(inSM = "YES"),
    st_centroid(ACS)[SM_Base, op = st_disjoint] %>%
      st_drop_geometry() %>%
      left_join(ACS) %>%
      st_sf() %>%
      mutate(inSM = "NO")) %>%
  filter(inSM == "YES") %>%
  dplyr::select(-inSM)

#long to wide form
ACS <-
  ACS %>%
  dplyr::select(-moe, -GEOID) %>%
  spread(variable, estimate) %>%
  dplyr::select(-geometry) %>%
  rename(vacantUnits = B25002_003,
         totalUnits = B25001_001,
         medHHInc = B19013_001,
         white = B01001A_001,
         population = B01003_001,
         ownerOcc = B07013_002,
         renterOcc = B07013_003,
         noHsDegree = B06009_002,
         maleAdult = B05003_008,
         femaleAdult = B05003_019,
         poverty = B06012_002,
         youthUnempVet = B21005_006,
         youthUnempNonVet = B21005_011,
         male1517 = B01001_006,
         male1819 = B01001_007,
         male20 = B01001_008,
         male21 = B01001_009,
         male2224 = B01001_010,
         male2529 = B01001_011,
         male3034 = B01001_012,
         female1819 = B01001_031,
         female20 = B01001_032,
         female21 = B01001_033,
         female2224 = B01001_034,
         female2529 = B01001_035,
         female3034 = B01001_036,
         median_age = B01002_001,
         medianage_male = B01002_002,
         medianage_female = B01002_003)
ACS <- 
  ACS %>%
  mutate(pctVacant = ifelse(totalUnits > 0, vacantUnits / totalUnits, 0),
         pctWhite = ifelse(population > 0, white / population, 0), 
         pctRenterOcc = renterOcc/ (renterOcc + ownerOcc),
         pctNoHS = noHsDegree/ (maleAdult + femaleAdult),
         pctPoverty = ifelse(population > 0, poverty / population, 0),
         youthUnemploy = (youthUnempVet + youthUnempNonVet) / (male1819 + male20 + male21 + male2224 + male2529 + male3034 + female1819 + female20 + female21 + female2224 + female2529 + female3034),
         pctMaleYouth = ifelse(population > 0, (male1517 + male1819 + male20 + male21 + male2224 + male2529 + male3034) / population, 0)) %>%
  dplyr::select(-totalUnits,-vacantUnits,-white,-renterOcc,-ownerOcc, -noHsDegree, -maleAdult, -femaleAdult, -youthUnempVet, -youthUnempNonVet, -male1517, -male1819, -male20, -male21, -male2224, -male2529, -male3034, -female1819, -female20, -female21, -female2224, -female2529, -female3034, -poverty)

#Fishnet
fishnet <- 
  st_make_grid(ACS, cellsize = 500) %>%
  st_sf()

fishnet <- fishnet %>%
  mutate(uniqueID = as.numeric(rownames(.)))


#Santa Monica Open Data
#crime
crime <- read.socrata("https://data.smgov.net/OData.svc/ia9m-wspt?Disposition='Arrest'") %>%
    dplyr::select(Y = latitude, X = longitude) %>%
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
    st_transform(st_crs(fishnet)) %>%
    mutate(Legend = "Crime")

violentCrime <- read.socrata("https://data.smgov.net/OData.svc/kn6p-4y74?UCR='0100' or UCR='0110' or UCR='0120' or UCR='0300' or UCR='0311' or UCR='0312' or UCR='0314' or UCR='0315' or UCR='0317' or UCR='0321' or UCR='0322' or UCR='0325'") %>%
  dplyr::select(Y = Latitude, X = Longitude) %>%
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
    st_transform(st_crs(fishnet)) %>%
    mutate(Legend = "Violent_Crime")



#trash/dumping
trash <- read.socrata("https://data.smgov.net/OData.svc/tsas-mvez?topic='Illegal Dumping'") %>%
  dplyr::select(Y = Latitude, X = Longitude) %>%
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
    st_transform(st_crs(fishnet)) %>%
    mutate(Legend = "Trash") 

#weather
library(riem)
library(dplyr)
library(lubridate)
weather.Panel <- 
  riem_measures(station = "KSMO", date_start = "2020-01-01", date_end = "2020-11-27") %>%
  dplyr::select(valid, tmpf, p01i, sknt) %>%
  replace(is.na(.), 0) %>%
    mutate(interval60 = ymd_h(substr(valid,1,13))) %>%
    mutate(week = week(interval60),
           dotw = wday(interval60, label=TRUE)) %>%
    group_by(interval60) %>%
    summarize(Temperature = max(tmpf),
              Precipitation = sum(p01i),
              Wind_Speed = max(sknt)) %>%
    mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))

#distance to downtown

#distance to water

#311 calls
call311 <- read.socrata("https://data.smgov.net/resource/tsas-mvez.json")
#https://www.smgov.net/santamonicaworks.aspx
  
streetlight <-  call311 %>% filter(topic=="Streetlights")%>%
  dplyr::select(Y = latitude, X = longitude) %>%
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
    st_transform(st_crs(fishnet)) %>%
    mutate(Legend = "streetlights")

signandmarking <- call311 %>% filter(topic=="Street Signs & Markings")%>%
  dplyr::select(Y = latitude, X = longitude) %>%
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
    st_transform(st_crs(fishnet)) %>%
    mutate(Legend = "markings")


socialservice <- call311 %>% filter(topic=="General Concerns/Social Service Request")%>%
  dplyr::select(Y = latitude, X = longitude) %>%
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
    st_transform(st_crs(fishnet)) %>%
    mutate(Legend = "servicerequest")

#ADD VARIABLE NEAR INDUSTRIAL SITES
parcel <-  read.socrata("https://data.smgov.net/resource/sa4y-7yah.json")
lu <- as.data.frame(unique(parcel$specificusetype))
harmful_lu <- parcel%>%filter(specificusetype=="Petroleum and Gas"|generalusetype=="Industrial")%>%
  dplyr::select(Y = center_lat, X = center_lon) %>%
    na.omit() %>%
    st_as_sf(coords = c("X", "Y"), crs = 4326, agr = "constant") %>%
    st_transform(st_crs(fishnet)) %>%
    mutate(Legend = "harmfullanduse")

#osm
#sport <- st_read("E:/Upenn/CPLN508/final project/EMS-Prediction/sport.geojson") %>%
  sport <- st_read("/Users/annaduan/Documents/GitHub/EMS-Prediction/sport.geojson") %>%
    st_transform(st_crs(fishnet))%>%
    mutate(Legend = "sport") 


ACS$row <- 1:nrow(ACS)

#CDC health data
CDC <-
  read.socrata("https://chronicdata.cdc.gov/OData.svc/k86t-wghb?stateabbr=CA") %>% 
  filter(placename == "Santa Monica") %>%
  dplyr::select(-stateabbr, -placename, -placefips, -place_tractid, -access2_crude95ci, -arthritis_crude95ci, -binge_crude95ci, -bphigh_crude95ci, -bpmed_crude95ci, -cancer_crude95ci, -casthma_crude95ci, -chd_crude95ci, -checkup_crude95ci, -cholscreen_crude95ci, -colon_screen_crude95ci, -copd_crude95ci, -corem_crude95ci, -corew_crude95ci, -csmoking_crude95ci, -dental_crude95ci, -diabetes_crude95ci, -highchol_crude95ci, -kidney_crude95ci, -lpa_crude95ci, -mammouse_crude95ci, -mhlth_crude95ci, -teethlost_crude95ci, -stroke_crude95ci, -sleep_crude95ci, -phlth_crude95ci, -paptest_crude95ci, -obesity_crude95ci) %>%
  rename(FIPS = tractfips,
         population = population2010,
         uninsured = access2_crudeprev,
arthritis = arthritis_crudeprev,
bingeDrink = binge_crudeprev,
highBloodPressure = bphigh_crudeprev,
bloodPressureMeds = bpmed_crudeprev,
cancer = cancer_crudeprev,
asthma = casthma_crudeprev,
heartDisease = chd_crudeprev,
doctorCheckups = checkup_crudeprev,
cholesterolScreen = cholscreen_crudeprev,
colonScreen65 = colon_screen_crudeprev,
pulmonaryDisease = copd_crudeprev,
clinicalServicesMen65 = corem_crudeprev,
clinicalServicesWomen65 = corew_crudeprev,
smoking = csmoking_crudeprev,
dentalVisits = dental_crudeprev,
diabetes = diabetes_crudeprev,
highCholesterol = highchol_crudeprev,
kidneyDisease = kidney_crudeprev,
noPhysicalActivity = lpa_crudeprev,
mammograms50 = mammouse_crudeprev,
poorMentalHealth = mhlth_crudeprev,
obese = obesity_crudeprev,
papTest = paptest_crudeprev,
poorPhysicalHealth = phlth_crudeprev,
sleepDeprived = sleep_crudeprev,
stroke = stroke_crudeprev,
noTeeth = teethlost_crudeprev,
geometry = geolocation) %>%
  dplyr::select(-population, -FIPS, -geometry)
  CDC$row <- 1:nrow(CDC)
  
tractData <- left_join(CDC,ACS, by = "row")


# ATTACH VARIABLES TO FISHNET
vars_net <- 
  rbind(violentCrime,trash, streetlight, signandmarking, socialservice, harmful_lu) %>%
  st_join(., fishnet, join=st_within) %>%
  st_drop_geometry() %>%
  group_by(uniqueID, Legend) %>%
  summarize(count = n()) %>%
    full_join(fishnet) %>%
    spread(Legend, count, fill=0) %>%
    st_sf() %>%
    dplyr::select(-`<NA>`) %>%
    na.omit() %>%
    ungroup()

vars_net_centroid <-
vars_net %>%
  st_centroid()

vars_net_tractData <- vars_net_centroid %>% 
  dplyr::select(uniqueID) %>%
  st_join(., tractData) %>%
  st_drop_geometry() %>%
  left_join(vars_net,.,by="uniqueID") %>%
  dplyr::select(NAME) %>%
   na.omit() %>%
    mutate(uniqueID = as.numeric(rownames(.)))


ggplot() + #AD - used this to diagnose hte issue with the missing data/geometries
  geom_sf(data = tractData, colour = "red", fill = "transparent") +
  geom_sf(data = fishnet, colour = "blue", fill = "transparent") +
  mapTheme()



# MAKE VARS_NET MAPPABLE
vars_net.long <- 
  gather(vars_net_acs, Variable, value, -geometry, -uniqueID)

vars <- unique(vars_net.long$Variable)
mapList <- list()


# MAKE NN FEATURES
st_c <- st_coordinates
st_coid <- st_centroid

vars_net_acs <-
  vars_net_acs %>%
    mutate(
      violentCrime.nn =
        nn_function(st_c(st_coid(vars_net)), st_c(violentCrime),3),
      trash.nn =
        nn_function(st_c(st_coid(vars_net)), st_c(trash),3),
      violentCrime.nn =
        nn_function(st_c(st_coid(vars_net)), st_c(violentCrime),3),
      streetlightissue.nn =
        nn_function(st_c(st_coid(vars_net)), st_c(streetlight),3),
      signandmarking.nn = 
        nn_function(st_c(st_coid(vars_net)), st_c(signandmarking),3),
      socialservice.nn = 
        nn_function(st_c(st_coid(vars_net)), st_c(socialservice),3),
      harmfullu.nn = 
        nn_function(st_c(st_coid(vars_net)), st_c(harmful_lu),1),
      sport.nn = 
        nn_function(st_c(st_coid(vars_net)), st_c(st_coid(sport)),1))

vars_net.long.nn <- 
  dplyr::select(vars_net_acs, ends_with(".nn")) %>%
    gather(Variable, value, -geometry)

vars <- unique(vars_net.long.nn$Variable)
mapList <- list()


#AD: not sure this is neighborhood- neighborhood association is different
#BC: sadly it's the only data we have got. I think these two may be very similar? http://www.city-data.com/nbmaps/neigh-Santa-Monica-California.html
#AD: fair enough! that makes sense
neighborhood <- st_read("https://opendata.arcgis.com/datasets/63595d717c494165b3c6b3b85c2463ae_0.geojson")%>%
      st_transform(st_crs(fishnet))




```


#Data exploratory
```{r map EMS incidents, cache=TRUE}
#EMS
EMS <- read.socrata("https://data.smgov.net/Public-Safety/Fire-Calls-for-Service/5y3u-5db4?call_type_description=Emergency Medical Service (EMS)")%>% 
dplyr::select (-census_block_2010_geoid, -census_tract_2010_geoid, -census_block_2000_geoid, -census_tract_2000_geoid)

EMS_int <- EMS %>% mutate (interval = difftime(cleared,received,units = "min"))


EMS_int$incident_date <- as.POSIXct(EMS_int$incident_date)

EMS_2020 <- subset(EMS_int,
     incident_date >= as.POSIXct('2020-01-01') &
     incident_date <= as.POSIXct('2020-11-27')
     ) 

EMS2020.sf <- na.omit(EMS_2020, cols=c("longitude", "latitude")) %>%  
    st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant") %>%
    st_transform('EPSG:2225')


emergencies <- EMS_int %>%
  dplyr::filter(., grepl('201', incident_date))  #filter for incidents since 2010
#  dplyr::filter(., grepl('Report', disposition)) %>%
emergencies.sf <- na.omit(emergencies, cols=c("longitude", "latitude")) %>%  
    st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant") %>%
    st_transform('EPSG:2225')


#EMS Net
EMS_net.count <- 
  dplyr::select(EMS2020.sf) %>% 
  mutate(countEMS = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(countEMS = replace_na(countEMS, 0),
         uniqueID = as.numeric(rownames(.)),
         cvID = sample(round(nrow(fishnet) / 24), size=nrow(fishnet), replace = TRUE))

EMS_net.resp <- 
  dplyr::select(EMS2020.sf) %>% 
  mutate(resp = na.omit(EMS2020.sf$interval)) %>% 
  aggregate(., fishnet, mean) %>%
  mutate(resp = replace_na(resp, 0),
         uniqueID = as.numeric(rownames(.)),
         cvID = sample(round(nrow(fishnet) / 24), size=nrow(fishnet), replace = TRUE))

EMS_net <- full_join(EMS_net.count, st_drop_geometry(EMS_net.resp), by = c("uniqueID"))

final_net <-
  inner_join(EMS_net, st_drop_geometry(vars_net_acs), by="uniqueID") #AD: something wrong here: it doesn't add the ACS columns...

#EMS SINCE 2010
EMS_net.count.emg <- 
  dplyr::select(emergencies.sf) %>% 
  mutate(countEMS = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(countEMS = replace_na(countEMS, 0),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet) / 24), size=nrow(fishnet), replace = TRUE))

EMS_net.resp.emg <- 
  dplyr::select(emergencies.sf) %>% 
  mutate(resp = na.omit(emergencies.sf$interval)) %>% 
  aggregate(., fishnet, mean) %>%
  mutate(resp = replace_na(resp, 0),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet) / 24), size=nrow(fishnet), replace = TRUE))

EMS_net.emg <- full_join(EMS_net.count.emg, st_drop_geometry(EMS_net.resp.emg), by = c("uniqueID", "cvID"))


#Map 2020 emergencies
ggplot() +
  geom_sf(data = EMS_net, aes(fill = countEMS, colour = countEMS)) +
#  geom_sf(data = ACS, fill = "transparent", colour = "white") +
  scale_fill_viridis(option = "A", name = "Incidents Per Cell") +
  scale_colour_viridis(option = "A", name = "Incidents Per Cell") +
  labs(title = "Observed EMS Calls Joined to Fishnet, 2020", subtitle = "Santa Monica, CA") +
  mapTheme()

ggplot() +
  geom_sf(data = SM_Base, fill = "black") +
  geom_sf(data = emergencies.sf, colour = "red", size = 0.1) +
  scale_colour_viridis(name = "1 Observed EMS", labels = "", option = "B") +
  labs(title = "Figure 1: Observed EMS, 2010-2019", subtitle = "Santa Monica, CA") +
  mapTheme()


#Map response time 2020
  ggplot() +
  geom_sf(data = EMS_net, aes(fill = resp, colour = resp)) +
  scale_fill_viridis(option = "A", name = "Minutes") +
  scale_colour_viridis(option = "A", name = "Minutes") +
  labs(title = "Average EMS Response Time Joined to Fishnet, 2020", subtitle = "Santa Monica, CA") +
  mapTheme()

#Map response time since 2010
  ggplot() +
  geom_sf(data = EMS_net.emg, aes(fill = resp, colour = resp)) +
  scale_fill_viridis(option = "A", name = "Minutes") +
  scale_colour_viridis(option = "A", name = "Minutes") +
  labs(title = "Figure 2: EMS Response Time Joined to Fishnet, 2010-2020", subtitle = "Santa Monica, CA") +
  mapTheme()  


ggplot() + 

  #geom_sf(data = ACS, fill = "black") +
  stat_density2d(data = data.frame(st_coordinates(emergencies.sf)), 
                 aes(X, Y, fill = ..level.., alpha = ..level..),
                 size = 0.1, bins = 200, geom = 'polygon') +
  scale_fill_gradient(low = "yellow", high = "red", 
                      breaks=c(0.000000003,0.00000003),
                      labels=c("Minimum","Maximum"), name = "Density") +
  scale_alpha(range = c(0.0, 0.5), guide = FALSE) +
  labs(title = "Density of EMS Incidents, Santa Monica") +
  mapTheme()

```

##maps
##plots
##spatial or space/time process



```{r moran}
##Prepare for moran's
library(spdep)
final_net.nb <- poly2nb(as_Spatial(final_net), queen=TRUE)  #AD: not working #?not sure why
final_net.weights <- nb2listw(final_net.nb, style="W", zero.policy=TRUE)

final_net.localMorans <- 
  cbind(
    as.data.frame(localmoran(final_net$countEMS, final_net.weights)),
    as.data.frame(final_net)) %>% 
    st_sf() %>%
      dplyr::select(EMS_Count = countEMS, 
                    Local_Morans_I = Ii, 
                    P_Value = `Pr(z > 0)`) %>%
      mutate(Significant_Hotspots = ifelse(P_Value <= 0.0000001, 1, 0)) %>%
      gather(Variable, Value, -geometry)

##distance to hotspots## 
final_net <-
  final_net %>% 
  mutate(EMS.isSig = 
           ifelse(localmoran(final_net$countEMS, 
                             final_net.weights)[,5] <= 0.0000001, 1, 0)) %>%
  mutate(EMS.isSig.dist = 
           nn_function(st_coordinates(st_centroid(final_net)),
                       st_coordinates(st_centroid(
                         filter(final_net, EMS.isSig == 1))), 1))
```

```{r time explotory}
EMS_2020 <- EMS_2020 %>%
  mutate(interval60 = floor_date(ymd_hms(received), unit = "hour"),
         interval15 = floor_date(ymd_hms(received), unit = "15 mins"),
         interval5 = floor_date(ymd_hms(received), unit = "5 mins"),
         interval1 = floor_date(ymd_hms(received), unit = "1 min"),
         week = week(interval60),
         month = month(interval60),
         dotw = wday(interval60, label=TRUE)) 


EMS2020.sf <- EMS2020.sf %>%
  mutate(interval60 = floor_date(ymd_hms(received), unit = "hour"),
         interval15 = floor_date(ymd_hms(received), unit = "15 mins"),
         week = week(interval60),
         dotw = wday(interval60, label=TRUE)) 



EMS_2010 <- emergencies %>%
  mutate(interval60 = floor_date(ymd_hms(received), unit = "hour"),
         interval15 = floor_date(ymd_hms(received), unit = "15 mins"),
         interval5 = floor_date(ymd_hms(received), unit = "5 mins"),
         interval1 = floor_date(ymd_hms(received), unit = "1 min"),
         week = week(interval60),
         dotw = wday(interval60, label=TRUE)) 

#add census tracts
dat_census <- st_join(EMS_2020 %>% 
          filter(is.na(longitude) == FALSE &
                   is.na(latitude) == FALSE) %>%
          st_as_sf(., coords = c("longitude", "latitude"), crs = 4326),
        ACSTracts %>%
          st_transform(crs=4326),
        join=st_intersects,
              left = TRUE) %>%
  mutate(longitude = unlist(map(geometry, 1)),
         latitude = unlist(map(geometry, 2)))%>%
  as.data.frame() 

library(dplyr)

dat_net <- st_join(EMS_2020 %>% 
          filter(is.na(longitude) == FALSE &
                   is.na(latitude) == FALSE) %>%
          st_as_sf(., coords = c("longitude", "latitude"), crs = 4326),
        fishnet %>%
          st_transform(crs=4326),
        join=st_intersects,
              left = TRUE) %>%
  mutate(longitude = unlist(map(geometry, 1)),
         latitude = unlist(map(geometry, 2)))%>%
  as.data.frame() 

#STUDY.PANEL
study.panel <- 
  expand.grid(interval60=unique(dat_net$interval60), 
              uniqueID = unique(dat_net$uniqueID)) %>%
  left_join(., dat_net %>%
              dplyr::select(uniqueID, longitude, latitude)%>% 
              distinct() %>%
              group_by(uniqueID) %>%
              slice(1))

study.panel.15 <- 
  expand.grid(interval15=unique(dat_net$interval15), 
              uniqueID = unique(dat_net$uniqueID)) %>%
  left_join(., dat_net %>%
              dplyr::select(uniqueID, longitude, latitude)%>% 
              distinct() %>%
              group_by(uniqueID) %>%
              slice(1))

install.packages("vctrs")

study.panel.2010 <- 
  expand.grid(interval60=unique(dat_net.2010$interval60),
              uniqueID = unique(dat_net.2010$uniqueID)) %>%
  left_join(., dat_net.2010 %>%
              dplyr::select(uniqueID, longitude, latitude)%>% 
              distinct() %>%
              group_by(uniqueID) %>%
              slice(1))

study.panel <- 
  dat_net %>%
  mutate(EMS_Counter = 1) %>%
  right_join(study.panel) %>% 
  group_by(interval60, uniqueID, longitude, latitude) %>% 
  summarize(EMS_Count = sum(EMS_Counter, na.rm=T)) %>%
  left_join(weather.Panel) %>%
  ungroup() %>%
  filter(is.na(uniqueID) == FALSE) %>%
  mutate(week = week(interval60),
         dotw = wday(interval60, label = TRUE))

study.panel.15 <- 
  dat_net %>%
  mutate(EMS_Counter = 1) %>%
  right_join(study.panel.15) %>% 
  group_by(interval15, uniqueID, longitude, latitude) %>% 
  summarize(EMS_Count = sum(EMS_Counter, na.rm=T)) %>%
  ungroup() %>%
  filter(is.na(uniqueID) == FALSE) %>%
  mutate(week = week(interval15),
         dotw = wday(interval15, label = TRUE))

study.panel.2010 <- 
  dat_net %>%
  mutate(EMS_Counter = 1) %>%
  right_join(study.panel.2010) %>% 
  group_by(interval60, uniqueID, longitude, latitude) %>% 
  summarize(EMS_Count = sum(EMS_Counter, na.rm=T)) %>%
  left_join(weather.Panel) %>%
  ungroup() %>%
  filter(is.na(uniqueID) == FALSE) %>%
  mutate(week = week(interval60),
         dotw = wday(interval60, label = TRUE))

study.panel <- 
  study.panel %>% 
  arrange(uniqueID, interval60) %>% 
  mutate(lagHour = dplyr::lag(EMS_Count,1),
         lag2Hours = dplyr::lag(EMS_Count,2),
         lag3Hours = dplyr::lag(EMS_Count,3),
         lag4Hours = dplyr::lag(EMS_Count,4),
         lag12Hours = dplyr::lag(EMS_Count,12),
         lag1day = dplyr::lag(EMS_Count,24)) %>% 
   mutate(day = yday(interval60))


study.panel.15 <- 
  study.panel.15 %>% 
  arrange(uniqueID, interval15) %>% 
  mutate(lag15 = dplyr::lag(EMS_Count,1),
         lag30 = dplyr::lag(EMS_Count,2),
         lag45 = dplyr::lag(EMS_Count,3),
         lag60 = dplyr::lag(EMS_Count,4)) %>% 
   mutate(day = yday(interval15))

study.panel.2010 <- 
  study.panel.2010 %>% 
  arrange(uniqueID, interval60) %>% 
  mutate(lagHour = dplyr::lag(EMS_Count,1),
         lag2Hours = dplyr::lag(EMS_Count,2),
         lag3Hours = dplyr::lag(EMS_Count,3),
         lag4Hours = dplyr::lag(EMS_Count,4),
         lag12Hours = dplyr::lag(EMS_Count,12),
         lag1day = dplyr::lag(EMS_Count,24)) %>% 
   mutate(day = yday(interval60))


as.data.frame(study.panel) %>%
    group_by(interval60) %>% 
    summarise_at(vars(starts_with("lag"), "EMS_Count"), mean, na.rm = TRUE) %>%
    gather(Variable, Value, -interval60, -EMS_Count) %>%
    mutate(Variable = factor(Variable, levels=c("lagHour","lag2Hours","lag3Hours","lag4Hours",
                                                "lag12Hours","lag1day", "lay2day")))%>%
    group_by(Variable) %>%  
    summarize(correlation = round(cor(Value, EMS_Count),2)) %>%
    kable (caption="Table 1: Time lag features and corelation", col.names = c('Time lag', 'Corelation')) %>%
    kable_styling()


as.data.frame(study.panel.15) %>%
    group_by(interval15) %>% 
    summarise_at(vars(starts_with("lag"), "EMS_Count"), mean, na.rm = TRUE) %>%
    gather(Variable, Value, -interval15, -EMS_Count) %>%
    mutate(Variable = factor(Variable, levels=c("lag15","lag30","lag45","lag60")))%>%
    group_by(Variable) %>%  
    summarize(correlation = round(cor(Value, EMS_Count),2)) %>%
    kable (caption="Table 2: Time lag features and corelation", col.names = c('Time lag', 'Corelation')) %>%
    kable_styling()

as.data.frame(study.panel.2010) %>%
    group_by(interval60) %>% 
    summarise_at(vars(starts_with("lag"), "EMS_Count"), mean, na.rm = TRUE) %>%
    gather(Variable, Value, -interval60, -EMS_Count) %>%
    mutate(Variable = factor(Variable, levels=c("lagHour","lag2Hours","lag3Hours","lag4Hours",
                                                "lag12Hours","lag1day")))%>%
    group_by(Variable) %>%  
    summarize(correlation = round(cor(Value, EMS_Count),2)) %>%
    kable (caption="Table 3: Time lag features and corelation", col.names = c('Time lag', 'Corelation')) %>%
    kable_styling()
```

```{r time explotory rush hour}
ggplot(EMS_2010 %>%
         group_by(week) %>%
         tally())+
  geom_line(aes(x = week, y = n))+
  labs(title="Figure 4.1: EMS trips, Santa Monica, 2010-2020 by week",
       x="week of the year", 
       y="Number of trips")+
  plotTheme

ggplot(EMS_2010 %>%
         group_by(dotw) %>%
         tally())+
  geom_line(aes(x = dotw, y = n, group = 1))+
  labs(title="Figure 4.2: EMS trips, Santa Monica, 2010-2020 by day of the week",
       x="Day", 
       y="Number of trips")+
  plotTheme

ggplot(EMS_2020 %>%
         group_by(week) %>%
         tally())+
  geom_line(aes(x = week, y = n))+
  labs(title="Figure 4.3: EMS trips, Santa Monica, 2020 by week",
       x="week of the year", 
       y="Number of trips")+
  plotTheme

ggplot(EMS_2020 %>%
         group_by(dotw) %>%
         tally())+
  geom_line(aes(x = dotw, y = n, group = 1))+
  labs(title="Figure 4.4: EMS trips, Santa Monica, 2020 by day of the week",
       x="Day", 
       y="Number of trips")+
  plotTheme

#on a RANDOM Wednesday
EMS_2020_W1 <- subset(EMS_2020, week==20 & dotw=="Wed")
ggplot(EMS_2020_W1 %>%
         group_by(interval60) %>%
         tally())+
  geom_line(aes(x = interval60, y = n))+
  labs(title="Figure 4.4: EMS trips, Santa Monica, 2020 by day of the week",
       x="Day", 
       y="Number of trips")+
  plotTheme

EMS_2020 %>% 
         mutate(time_of_day = case_when(hour(interval60) < 7 | hour(interval60) > 18 ~ "Overnight",
                                 hour(interval60) >= 7 & hour(interval60) < 10 ~ "AM Rush",
                                 hour(interval60) >= 10 & hour(interval60) < 15 ~ "Mid-Day",
                                 hour(interval60) >= 15 & hour(interval60) <= 18 ~ "PM Rush"))%>%
         group_by(interval60, reporting_district, time_of_day) %>%
         tally()%>%
  group_by(time_of_day, reporting_district,)%>%
  summarize(mean_trips = mean(n))%>%
  ggplot()+
  geom_histogram(aes(mean_trips), binwidth = 1)+
  labs(title="Figure 4.2: Mean Number of Hourly Trips Per reporting district. Philadelphia, Nov, 2018",
       x="Number of trips", 
       y="Frequency")+
  facet_wrap(~time_of_day)+
  plotTheme

#hour of dotw
ggplot(EMS_2020 %>% mutate(hour = hour(received)))+
     geom_freqpoly(aes(hour, color = dotw), binwidth = 1)+
  labs(title="Figure 4.3: EMS calls in Santa Monica, by day of the week, 2020",
       x="Hour", 
       y="Trip Counts")+
     plotTheme


ggplot(EMS_2020 %>% 
         mutate(hour = hour(received),
                weekend = ifelse(dotw %in% c("Sun", "Sat"), "Weekend", "Weekday")))+
     geom_freqpoly(aes(hour, color = weekend), binwidth = 1)+
  labs(title="Figure 4.4: EMS calls in Santa Monica - weekend vs weekday, 2020",
       x="Hour", 
       y="Trip Counts")+
     plotTheme

#origin map
ggplot()+
  geom_sf(data = neighborhood %>%
          st_transform(crs=4326), fill = "white")+
  geom_point(data = dat_census %>% 
            mutate(hour = hour(received),
                weekend = ifelse(dotw %in% c("Sun", "Sat"), "Weekend", "Weekday"),
                time_of_day = case_when(hour(interval60) < 7 | hour(interval60) > 18 ~ "Overnight",
                                 hour(interval60) >= 7 & hour(interval60) < 10 ~ "AM Rush",
                                 hour(interval60) >= 10 & hour(interval60) < 15 ~ "Mid-Day",
                                 hour(interval60) >= 15 & hour(interval60) <= 18 ~ "PM Rush"))%>%
              group_by(reporting_district, latitude, longitude, weekend, time_of_day) %>%
              tally(),
            aes(x=longitude, y = latitude, color = n), 
            fill = "transparent", alpha = 0.4, size = 1)+
  scale_colour_viridis(direction = -1,
  discrete = FALSE, option = "D")+
  ylim(min(dat_census$latitude), max(dat_census$latitude))+
  xlim(min(dat_census$longitude), max(dat_census$longitude))+
  facet_grid(weekend ~ time_of_day)+
  labs(title="Figure 4.5: EMS calls per hr by reporting district. Santa Monica, 2020")+
  mapTheme


```

```{r animation}

week20 <-
  filter(EMS2020.sf, week == 20)

week20.panel <-
  expand.grid(
    interval60 = unique(week20$interval60),
    reporting_district = unique(EMS2020.sf$reporting_district))

ems.animation.data <-
  mutate(week20, Trip_Counter = 1) %>%
    right_join(week20.panel) %>% 
    group_by(interval60, reporting_district) %>%
    summarize(Trip_Count = sum(Trip_Counter, na.rm=T)) %>% 
    ungroup() %>% 
    st_sf() %>%
    mutate(Trips = case_when(Trip_Count == 0 ~ "0 trips",
                             Trip_Count == 1 ~ "1 trips")) %>%
    mutate(Trips = fct_relevel(Trips, "0 trips","1 trips"))


library(gganimate)
library(gifski)
EMS_animation <-
  ggplot() +
    geom_sf(data = ems.animation.data, aes(col = Trips), size= 5, show.legend = "point")+
    geom_sf(data = neighborhood, color = "grey", fill = "transparent")+
    scale_fill_manual(values = c("green", "yellow", "orange","red")) +
    labs(title = "Figure 4.6: EMS calls for one week in May 2020",
         subtitle = "1 hour intervals: {current_frame}") +
    transition_manual(interval60) +
    mapTheme

animate(EMS_animation, duration=20, renderer = gifski_renderer())

anim_save("ems_local", EMS_animation, duration=20, renderer = gifski_renderer())
```

```{r histogram of incidents}

#final_net <- 
#  st_centroid(final_net) %>%
 #   st_join(dplyr::select(neighborhoods, name)) %>%
 #   st_join(dplyr::select(policeDistricts, District)) %>%
 #     st_drop_geometry() %>%
 #     left_join(dplyr::select(final_net, geometry, uniqueID)) %>%
 #     st_sf() %>%
  #    na.omit()

ggplot(data = final_net, aes(x=countEMS)) +
  geom_histogram() +
  labs(title = "Figure 3: Distribution of EMS Incidents, 2010-2019", subtitle = "Santa Monica, CA", x = "Fishnet Cells", y = "EMS Incidents Observed") +
  plotTheme()
```

```{r map risk factors}
#get rid of NAME variable (census tract name), select preferred features
vars_net_noname <- subset(vars_net_acs, select = -c(uniqueID.x)) %>%
  dplyr::select(harmfullanduse, markings, servicerequest, streetlights, Trash, Violent_Crime, median_age, population, medHHInc, pctVacant, pctWhite, pctRenterOcc, pctNoHS, pctPoverty, youthUnemploy, pctMaleYouth, violentCrime.nn, trash.nn, streetlightissue.nn, signandmarking.nn, socialservice.nn, harmfullu.nn, sport.nn)

#make vars_net.long to use for mapping
vars_net.long <-
   gather(vars_net_noname, Variable, value, -geometry)

#select features to show in multiple map
vars_net.long.select <-     
   gather(vars_net_noname, Variable, value, -geometry) %>%
  dplyr::filter(Variable == "medHHInc" | Variable == "pctMaleYouth"| Variable == "pctNoHS"| Variable == "pctPoverty" | Variable == "markings" | Variable == "servicerequest" | Variable == "Trash" | Variable == "youthUnemploy")

vars_net.long.select2 <-     
   gather(vars_net_noname, Variable, value, -geometry) %>%
  dplyr::filter(Variable != "medHHInc" & Variable != "pctMaleYouth"& Variable != "pctNoHS"& Variable != "pctPoverty" & Variable != "markings" & Variable != "servicerequest" & Variable != "Trash" & Variable != "youthUnemploy")

#make list of unique variables
vars <- unique(vars_net.long.select$Variable)
mapList <- list()

vars2 <- unique(vars_net.long.select2$Variable)
mapList2 <- list()

#map risk factors
for(i in vars){
  mapList[[i]] <- 
    ggplot() +
      geom_sf(data = filter(vars_net.long, Variable == i), aes(fill=value), colour=NA) +
      scale_fill_viridis(option = "A", name="") +
      labs(title=i) +
      mapTheme() +
    theme(plot.title = element_text(size=10))}

for(i in vars2){
  mapList2[[i]] <- 
    ggplot() +
      geom_sf(data = filter(vars_net.long, Variable == i), aes(fill=value), colour=NA) +
      scale_fill_viridis(option = "A", name="") +
      labs(title=i) +
      mapTheme() +
    theme(plot.title = element_text(size=10))}

do.call(grid.arrange,c(mapList, ncol = 3, top = "Figure 4: Risk Factors by Fishnet"))

do.call(grid.arrange,c(mapList2, ncol = 3, top = "Figure 4: Risk Factors by Fishnet"))

```

```{r weather, fig.height=5, fig.width=10}
library(ggplot2)
library(gridExtra)
grid.arrange(
  ggplot(weather.Panel, aes(interval60,Precipitation)) + geom_line() + 
  labs(title="Precipitation", x="Month", y="Precipitation") + plotTheme(),
  ggplot(weather.Panel, aes(interval60,Wind_Speed)) + geom_line() + 
    labs(title="Wind Speed", x="Month", y="Wind Speed") + plotTheme(),
  ggplot(weather.Panel, aes(interval60,Temperature)) + geom_line() + 
    labs(title="Temperature", x="Month", y="Temperature") + plotTheme(),
  top="Weather Data - Santa Monica CA - Jan - Nov 2020")
```


```{r plot times}


ggplot(EMS_2020 %>% mutate(hour = hour(interval60)))+
     geom_freqpoly(aes(hour, color = dotw), binwidth = 1)+
  labs(title="EMS Calls in Santa Monica, by day of week, 2010-2020",
       x="Hour", 
       y="EMS Calls")+
     plotTheme()


ggplot(EMS_2020 %>% mutate(hour = hour(interval60)))+
     geom_freqpoly(aes(month), binwidth = 1)+
  labs(title="EMS Calls in Santa Monica by month, 2020",
       x="Month", 
       y="EMS Calls")+
     plotTheme()
```

```{r scatterplots}
correlation.long <-
  st_drop_geometry(final_net) %>%
    dplyr::select(-uniqueID, -cvID, -NAME) %>%
    gather(Variable, Value, -countEMS) %>%
  mutate(Value = as.numeric(Value))

correlation.cor <-
  correlation.long %>%
    group_by(Variable) %>%
    summarize(correlation = cor(Value, countEMS, use = "complete.obs"))
    
ggplot(correlation.long, aes(Value, countEMS)) +
  geom_point(size = 0.1) +
  geom_text(data = correlation.cor, aes(label = paste("r =", round(correlation, 2))),
            x=-Inf, y=Inf, vjust = 1.5, hjust = -.1) +
  geom_smooth(method = "lm", se = FALSE, colour = "black") +
  facet_wrap(~Variable, ncol = 3, scales = "free") +
  labs(title = "Figure 6: Observed Arrests as a Function of Risk Factors", subtitle = "Chicago, IL") +
  plotTheme()
```



#modeling
```{r modeling}
reg.all <- c("markings", "medHHInc", "median_age", "medianage_female", "medianage_male", "notWorking", "obese", "pctMaleYouth", "pctNoHS", "pctPoverty", "pctRenterOcc", "pctVacant", "pctWhite", "population", "resp", "servicerequest", "signandmarking.nn", "sport.nn", "streetlightissue.nn", "Trash", "trash.nn", "Violent_Crime", "youthUnemploy", "deoayedMedCare", "diagnoseAsthma", "diagnoseDiabetes", "diagnoseHeartDisease", "harmfullanduse", "harmfullu.nn", "socialservice.nn", "streetlights", "uninsured", "violentCrime.nn")


```

```{r temperal model}

ride.Train <- filter(study.panel, week <= 32) 
ride.Test <- filter(study.panel, week > 32)

reg_tem <- 
  lm(EMS_Count ~  hour(interval60) + dotw + Temperature + Precipitation +
                   lagHour + lag2Hours +lag3Hours +lag12Hours + lag1day, 
     data=ride.Train)

##nesting
ride.Test.weekNest <- 
  ride.Test %>%
  nest(-week) 

model_pred <- function(dat, fit){
   pred <- predict(fit, newdata = dat)}

week_predictions <- 
  ride.Test.weekNest %>% 
    mutate(Time_Space_FE_timeLags = map(.x = data, fit = reg_tem, .f = model_pred)) %>% 
    gather(Regression, Prediction, -data, -week) %>%
    mutate(Observed = map(data, pull, EMS_Count),
           Absolute_Error = map2(Observed, Prediction,  ~ abs(.x - .y)),
           MAE = map_dbl(Absolute_Error, mean, na.rm = TRUE),
           sd_AE = map_dbl(Absolute_Error, sd, na.rm = TRUE))

#PLOT
week_predictions %>%
  dplyr::select(week, Regression, MAE) %>%
  gather(Variable, MAE, -Regression, -week) %>%
  ggplot(aes(week, MAE)) + 
    geom_bar(aes(fill = Regression), position = "dodge", stat="identity") +
    scale_fill_manual(values = palette5) +
    labs(title = "Figure 5.1: Mean Absolute Errors by model specification and week") +
  plotTheme
#the mae is much lower when we use uniqueID instead of reporting-district
#PLOT AGAINST ACTUAL SERIES
week_predictions %>% 
    mutate(interval60 = map(data, pull, interval60),
           reporting_district = map(data, pull, reporting_district), 
           latitude = map(data, pull, latitude), 
           longitude = map(data, pull, longitude)) %>%
    dplyr::select(interval60, reporting_district, longitude, latitude, Observed, Prediction, Regression) %>%
    unnest() %>%
  filter(Regression == "Time_Space_FE_timeLags") %>% ##regresstion
  group_by(reporting_district, latitude, longitude) %>%
  summarize(MAE = mean(abs(Observed-Prediction), na.rm = TRUE))%>%
ggplot(.)+
  geom_sf(data = (neighborhood %>%
    st_transform(st_crs(4326))), color = "grey", fill = "transparent")+
  geom_point(aes(x = longitude, y = latitude, color = MAE), 
             fill = "transparent", alpha = 0.4)+
  scale_colour_viridis(direction = -1,
  discrete = FALSE, option = "D")+
  ylim(min(dat_census$latitude), max(dat_census$latitude))+
  xlim(min(dat_census$longitude), max(dat_census$longitude))+
  labs(title="Figure 5.3: Mean Abs Error, Test Set, Model 4")+
  mapTheme
```

#cross-validation
```{r CV}
#crossValidate function
crossValidate <- function(dataset, id, dependentVariable, indVariables) {

allPredictions <- data.frame()
cvID_list <- unique(dataset[[id]])

for (i in cvID_list) {

  thisFold <- i
  cat("This hold out fold is", thisFold, "\n")

  fold.train <- filter(dataset, dataset[[id]] != thisFold) %>% as.data.frame() %>% 
                dplyr::select(id, geometry, indVariables, dependentVariable)
  fold.test  <- filter(dataset, dataset[[id]] == thisFold) %>% as.data.frame() %>% 
                dplyr::select(id, geometry, indVariables, dependentVariable)
  
  regression <-
    glm(countEMS ~ ., family = "poisson", 
      data = fold.train %>% 
      dplyr::select(-geometry, -id))
  
  thisPrediction <- 
    mutate(fold.test, Prediction = predict(regression, fold.test, type = "response"))
    
  allPredictions <-
    rbind(allPredictions, thisPrediction)
    
  }
  return(st_sf(allPredictions))
}


#all variables
reg.cv <- crossValidate(
  dataset = final_net,
  id = "cvID.x",
  dependentVariable = "countEMS",
  indVariables = reg.all) %>%
    dplyr::select(cvID = cvID, countEMS, Prediction, geometry)


reg.summary <- 
    mutate(reg.cv,           Error = Prediction - countEMS,
                             Regression = "Random k-fold CV: Just Risk Factors") %>%
    st_sf() 
```


#?
##f. Provide additional maps and data visualizations to show that your model is useful.
##g. Talk about how your analysis meets the use case you set out to address.
##h. What could you do to make the analysis better?
